name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - release/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: wemogy/next-version-action@2.0.2
        id: next-version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Create Nuget package
        run: nuget pack -Version ${{ steps.next-version.outputs.next-version }}

      - name: Publish Nuget package
        run: dotnet nuget push **/**/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.PUBLIC_NUGET_TOKEN }}
        working-directory: ${{ steps.release-version.outputs.folder }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.next-version.outputs.next-version-name }}
          name: Version ${{ steps.next-version.outputs.next-version }}
          generate_release_notes: true
          files: |
            **/**/*.nupkg
